/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PedidoEntity { 
    id?: string;
    idPlato?: string;
    idUser?: string;
    modificaciones?: Array<string>;
    estado?: PedidoEntity.EstadoEnum;
    entrega?: string;
}
export namespace PedidoEntity {
    export const EstadoEnum = {
        Preparing: 'PREPARING',
        Delivering: 'DELIVERING',
        Delivered: 'DELIVERED'
    } as const;
    export type EstadoEnum = typeof EstadoEnum[keyof typeof EstadoEnum];
}


