/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserEntity { 
    id?: string;
    nickname?: string;
    email?: string;
    password?: string;
    iconUrl?: string;
}

